In [4]:
import keras
from keras.preprocessing.text import one_hot

In [5]:
sent=['the glass of milk','the glass of juice','the cup of tea','i am a good developer',
      'understand the meaning of words','your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size=10000

In [8]:
df=[one_hot(words,voc_size) for words in sent]
df

[[3703, 3545, 8126, 9404],
 [3703, 3545, 8126, 2626],
 [3703, 3240, 8126, 2859],
 [9094, 7276, 1565, 6302, 446],
 [5705, 3703, 176, 8126, 7371],
 [4684, 6289, 5361, 6302]]

In [11]:
from keras.models import Sequential
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding
import numpy as np


In [12]:
df_length=8
emb=pad_sequences(df,padding='pre',maxlen=df_length)
emb

array([[   0,    0,    0,    0, 3703, 3545, 8126, 9404],
       [   0,    0,    0,    0, 3703, 3545, 8126, 2626],
       [   0,    0,    0,    0, 3703, 3240, 8126, 2859],
       [   0,    0,    0, 9094, 7276, 1565, 6302,  446],
       [   0,    0,    0, 5705, 3703,  176, 8126, 7371],
       [   0,    0,    0,    0, 4684, 6289, 5361, 6302]])

In [13]:
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=df_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(emb))

[[[-4.88149188e-02  1.38456561e-02  2.28932761e-02  1.20052323e-02
   -4.59753051e-02  9.74689797e-03 -1.99673772e-02  1.22464411e-02
   -3.26864012e-02 -2.72955652e-02]
  [-4.88149188e-02  1.38456561e-02  2.28932761e-02  1.20052323e-02
   -4.59753051e-02  9.74689797e-03 -1.99673772e-02  1.22464411e-02
   -3.26864012e-02 -2.72955652e-02]
  [-4.88149188e-02  1.38456561e-02  2.28932761e-02  1.20052323e-02
   -4.59753051e-02  9.74689797e-03 -1.99673772e-02  1.22464411e-02
   -3.26864012e-02 -2.72955652e-02]
  [-4.88149188e-02  1.38456561e-02  2.28932761e-02  1.20052323e-02
   -4.59753051e-02  9.74689797e-03 -1.99673772e-02  1.22464411e-02
   -3.26864012e-02 -2.72955652e-02]
  [-4.07896154e-02 -3.92385609e-02  9.34988260e-03 -4.01181206e-02
    3.51057909e-02 -1.78276077e-02 -2.01547276e-02  1.78346373e-02
   -3.82959619e-02  1.34899132e-02]
  [ 4.32253741e-02  2.14290060e-02  4.14149798e-02  9.95321199e-03
   -1.22870579e-02 -2.97863968e-02  2.14702822e-02 -4.69166413e-02
   -4.63888794e-

In [19]:
emb[0]

array([   0,    0,    0,    0, 3703, 3545, 8126, 9404])

In [21]:
print(model.predict(emb)[0])

[[-0.04881492  0.01384566  0.02289328  0.01200523 -0.04597531  0.0097469
  -0.01996738  0.01224644 -0.0326864  -0.02729557]
 [-0.04881492  0.01384566  0.02289328  0.01200523 -0.04597531  0.0097469
  -0.01996738  0.01224644 -0.0326864  -0.02729557]
 [-0.04881492  0.01384566  0.02289328  0.01200523 -0.04597531  0.0097469
  -0.01996738  0.01224644 -0.0326864  -0.02729557]
 [-0.04881492  0.01384566  0.02289328  0.01200523 -0.04597531  0.0097469
  -0.01996738  0.01224644 -0.0326864  -0.02729557]
 [-0.04078962 -0.03923856  0.00934988 -0.04011812  0.03510579 -0.01782761
  -0.02015473  0.01783464 -0.03829596  0.01348991]
 [ 0.04322537  0.02142901  0.04141498  0.00995321 -0.01228706 -0.0297864
   0.02147028 -0.04691664 -0.00463889  0.01875397]
 [-0.01439763 -0.04943901  0.02737235 -0.00032996  0.04263673 -0.01240043
   0.02635309 -0.00371472 -0.04793188  0.00687347]
 [-0.01751568  0.01647064  0.0363237  -0.01832122  0.03914234 -0.0218868
  -0.03605521 -0.03228338 -0.03479086  0.04959108]]


In [22]:
import keras
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import one_hot
from keras.layers import Embedding
from keras.models import Sequential

In [23]:
sent=['the glass of milk','the glass of juice','the cup of tea','i am a good developer',
      'understand the meaning of words','your videos are good']

In [24]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [25]:
voc_size=10000

In [26]:
dim=10

In [31]:
length=8
df=[one_hot(words,voc_size) for words in sent]
df

[[3703, 3545, 8126, 9404],
 [3703, 3545, 8126, 2626],
 [3703, 3240, 8126, 2859],
 [9094, 7276, 1565, 6302, 446],
 [5705, 3703, 176, 8126, 7371],
 [4684, 6289, 5361, 6302]]

In [ ]:
model=Sequential()
model.add(E)

In [35]:
emb=pad_sequences(Embedding(voc_size,dim,input_length=length))
emb

ValueError: `sequences` must be iterable.

In [36]:
import keras
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding
from keras.models import Sequential

In [37]:
sent=['the glass of milk','the glass of juice','the cup of tea','i am a good developer',
      'understand the meaning of words','your videos are good']

In [38]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [39]:
voc_size=10000
dim=10

In [40]:
df=[one_hot(words,voc_size) for words in sent]
df

[[3703, 3545, 8126, 9404],
 [3703, 3545, 8126, 2626],
 [3703, 3240, 8126, 2859],
 [9094, 7276, 1565, 6302, 446],
 [5705, 3703, 176, 8126, 7371],
 [4684, 6289, 5361, 6302]]

In [41]:
emb=pad_sequences(df,maxlen=8,padding='pre')
emb

array([[   0,    0,    0,    0, 3703, 3545, 8126, 9404],
       [   0,    0,    0,    0, 3703, 3545, 8126, 2626],
       [   0,    0,    0,    0, 3703, 3240, 8126, 2859],
       [   0,    0,    0, 9094, 7276, 1565, 6302,  446],
       [   0,    0,    0, 5705, 3703,  176, 8126, 7371],
       [   0,    0,    0,    0, 4684, 6289, 5361, 6302]])

In [43]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=8))
model.compile('adam','mse')
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [44]:
emb[0]

array([   0,    0,    0,    0, 3703, 3545, 8126, 9404])

In [45]:
print(model.predict(emb)[0])

[[ 0.02893845 -0.04278136  0.00959117  0.01054429  0.01157656 -0.00502093
   0.04653821 -0.02558572 -0.03852822  0.02796509]
 [ 0.02893845 -0.04278136  0.00959117  0.01054429  0.01157656 -0.00502093
   0.04653821 -0.02558572 -0.03852822  0.02796509]
 [ 0.02893845 -0.04278136  0.00959117  0.01054429  0.01157656 -0.00502093
   0.04653821 -0.02558572 -0.03852822  0.02796509]
 [ 0.02893845 -0.04278136  0.00959117  0.01054429  0.01157656 -0.00502093
   0.04653821 -0.02558572 -0.03852822  0.02796509]
 [ 0.02763252 -0.00498134  0.03104173  0.01713339  0.04269776  0.01571293
  -0.0215435  -0.01728521 -0.03917838  0.03806773]
 [-0.02629542  0.00108879  0.02858258 -0.04991428  0.00246952 -0.00731017
  -0.03599428 -0.00925834  0.03443125  0.02754362]
 [-0.03641178 -0.01782118 -0.03362159  0.02568972  0.03686073 -0.04840351
  -0.00061224  0.00497288  0.03052567 -0.01868712]
 [ 0.01501068 -0.02512971 -0.01942289 -0.04539361 -0.01278912 -0.04584069
  -0.00254294  0.04898596  0.00435079  0.00808398]]